# Example 6 - Test

In [1]:
from CircuitCalculator.Circuit.circuit import Circuit, transform_circuit
import CircuitCalculator.Circuit.components as ccp
from CircuitCalculator.Circuit.solution import DCSolution
import numpy as np

In [2]:
R1, R2, R3, R4, R5 = 10, 20, 30, 40, 50
Vs1, Vs2 = 1, 2
circuit = Circuit([
    ccp.dc_voltage_source(V=Vs1, id='Vs1', nodes=('0', '1')),
    ccp.dc_voltage_source(V=Vs2, id='Vs2', nodes=('3', '2')),
    ccp.resistor(R=R1, id='R1', nodes=('1', '2')),
    ccp.resistor(R=R2, id='R2', nodes=('2', '0')),
    ccp.resistor(R=R3, id='R3', nodes=('2', '3')),
    ccp.resistor(R=R4, id='R4', nodes=('3', '4')),
    ccp.resistor(R=R5, id='R5', nodes=('4', '0')),
    ccp.ground(nodes=('0', ))
])
network = transform_circuit(circuit, w=0)

In [3]:
solution = DCSolution(circuit)
print(f'phi 1={solution.get_potential("1"):2.2f}V')
print(f'phi 2={solution.get_potential("2"):2.2f}V')
print(f'phi 3={solution.get_potential("3"):2.2f}V')
print(f'phi 4={solution.get_potential("4"):2.2f}V')

phi 1=-1.00V
phi 2=-2.21V
phi 3=-0.21V
phi 4=0.54V


In [4]:
G1, G2, G3, G4, G5 = 1/R1, 1/R2, 1/R3, 1/R4, 1/R5
A = np.array([
    # [ G2+G5,    0,      -G2,     0,   -G5,  1,  0],
    [     0,   G1,      -G1,     0,     0, -1,  0],
    [    -G2, -G1, G1+G2+G3,   -G3,     0,  0, -1],
    [      0,   0,      -G3, G3+G4,   -G4,  0,  1],
    [    -G5,   0,        0,   -G4, G4+G5,  0,  0],
    [     -1,   1,        0,     0,     0,  0,  0],
    [      0,   0,        1,    -1,     0,  0,  0],
    [      1,   0,        0,     0,     0,  0,  0]
])
print(np.linalg.cond(A))

I = np.array([0, 0, 0, 0, Vs1, Vs2, 0])

x = np.linalg.solve(A, I)
phi = x[:5]
i = x[5:]
print(phi)
print(i)

42.06949542621331
[-0.          1.          0.75862069 -1.24137931 -0.68965517]
[0.02413793 0.08045977]


In [5]:
G1, G2, G3, G4, G5 = 1/R1, 1/R2, 1/R3, 1/R4, 1/R5
A = np.array([
    [ G1,      -G1,     0,     0, -1,  0],
    [-G1, G1+G2+G3,   -G3,     0,  0, -1],
    [  0,      -G3, G3+G4,   -G4,  0,  1],
    [  0,        0,   -G4, G4+G5,  0,  0],
    [  1,        0,     0,     0,  0,  0],
    [  0,        1,    -1,     0,  0,  0],
])
print(np.linalg.cond(A))

I = np.array([0, 0, 0, 0, Vs1, Vs2])

x = np.linalg.solve(A, I)
phi = x[:4]
i = x[4:]
print(phi)
print(i)

38.87388384698125
[ 1.          0.75862069 -1.24137931 -0.68965517]
[0.02413793 0.08045977]


In [6]:
from CircuitCalculator.Network.NodalAnalysis.node_analysis import nodal_analysis_coefficient_matrix, nodal_analysis_constants_vector

In [7]:
A = nodal_analysis_coefficient_matrix(network)
b = nodal_analysis_constants_vector(network)


x = np.linalg.solve(A, b)
phi = x[:4]
i = x[4:]
print(phi.real)
print(i.real)


[ 1.          0.75862069 -1.24137931 -0.68965517]
[0.02413793 0.08045977]
